######################################################
##### SCRIPT DEL PROGRAMA "R" PARA LA PRÁCTICA 1.A. ####
######################################################

# EL ALUMNO DEBE INSERTAR LOS SEIS VALORES DE INTENSIDAD EN MILIAMPERIOS (mA)
# ENTRE LOS PARENTESIS (ABAJO). LOS VALORES VAN SEPARADOS POR LAS COMAS. 
# SE USA UN PUNTO COMO DECIMAL (Y NO UNA COMA):
I = c( , , , , , )  

# ABAJO SE INSERTAN LOS SEIS VALORES CORRESPONDIENTES DE VOLTAJE EN VOLTIOS (V):
V = c( , , , , , ) 

# PASAMOS LAS INTENSIDADES DE MILLAMPERIOS A AMPERIOS:
I = 1e-3 * I 

# PINTAMOS EL GRÁFICO DE LOS VALORES EXPERIMENTALES DE VOLTAJE 
# FRENTE A LOS VALORES DE INTENSIDAD, PONIENDO LOS NOMBRES DE LAS MAGNTITUDES
# EN LOS EJES:
plot(I,V, xlab="intensidad (A)", ylab="voltaje (V)")

# REALIZAMOS LA REGRESIÓN LINEAL DE LOS DATOS Y GUARDAMOS TODA INFORMACIÓN ACERCA
# DE LA REGRESIÓN EN UN OBJETO QUE LLAMAMOS "ajuste1":
ajuste1 = lm(V ~ I)

# PINTAMOS LA LÍNEA DE REGRESIÓN JUNTO CON EL GRÁFICO DE LOS DATOS EXPERIMENTALES: 
abline(ajuste1, col = "red")

# LOS SIGUIENTES COMANDOS SON PARA QUE SALGAN EL VALOR DE LA PENDIENTE Y SU ERROR
# EN LA VENTANILLA "R Console" 
cat("La pendiente es: ",coef(ajuste1)[2],"OHMIOS\n")
cat("El error de la pendiente es: ",summary(ajuste1)$coef[4],"OHMIOS\n")

